<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtregno</name>
   <tag></tag>
   <elementGuidId>7b97d7ea-a696-4b2d-94b6-d1f261feb012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtregno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtregno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0d39792-1b1d-439b-bfab-3588e557269d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtregno</value>
      <webElementGuid>49e54491-e753-401d-8d68-9d58ada37bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e9be02d-26ac-4abe-bd73-459066e36489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtregno</value>
      <webElementGuid>ae835c0a-b737-4178-a9f2-da2d302d0b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label_field</value>
      <webElementGuid>08fba86b-a398-4238-b5b9-8bf4e0ac2ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reg.No</value>
      <webElementGuid>3c3dfa3f-b905-424a-8433-8696eeffdc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtregno&quot;)</value>
      <webElementGuid>c5907c03-093b-4ae5-8beb-80a18a3701ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtregno']</value>
      <webElementGuid>4c54cd2c-812e-4786-a9fa-f80fe8f58ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ctl01']/div[3]/fieldset/div/input</value>
      <webElementGuid>86dee741-5b13-445d-b497-eb431249551d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>a94282f6-addc-4673-85a6-f1a36c89788d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtregno' and @type = 'text' and @id = 'txtregno' and @placeholder = 'Reg.No']</value>
      <webElementGuid>642afdfc-b926-4490-ba1a-79db830faca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
