<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_txtdate</name>
   <tag></tag>
   <elementGuidId>808515e8-69ff-435c-a33c-2dbea372a170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24c9346f-5e95-4e35-a09a-59e69cc7a137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtdate</value>
      <webElementGuid>386c76d1-8f61-4167-a152-44e65e52fcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b1cce92-a003-4047-93b6-30b1d71914bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtdate</value>
      <webElementGuid>85d2060b-6b66-4f7c-b543-c823736494a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DOB</value>
      <webElementGuid>c0d84e51-b97c-4465-81bb-f195bd125dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtdate&quot;)</value>
      <webElementGuid>d1d20531-2182-453a-8c9c-c991abcbfbb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtdate']</value>
      <webElementGuid>cb115994-13dd-415a-8a01-e8aa8640ec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ctl01']/div[3]/fieldset/div[2]/input</value>
      <webElementGuid>e3289b3f-d321-4d2f-a07a-97960ed11cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/input</value>
      <webElementGuid>d1501fdf-97f9-40bb-9efe-f3e83b607176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtdate' and @type = 'text' and @id = 'txtdate' and @placeholder = 'DOB']</value>
      <webElementGuid>97df41c9-e73a-41df-b952-cd4983e45877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
